export const blogCardData = [
  {
    category: "Update",
    blogImg: "/assets/images/blog-img-1.jpg",
    title: "Remote Work Opportunities Are Rising Worldwide",
    date: "15 October, 2025",
    authorImage: "/assets/images/user-avatar-1.png",
    authorName: "Daniel Brooks",
    authorPosition: "Global Hiring Specialist",
  },
  {
    category: "Insight",
    blogImg: "/assets/images/blog-img-2.jpg",
    title: "How AI is Transforming the Job Market",
    date: "20 November, 2025",
    authorImage: "/assets/images/user-avatar-2.png",
    authorName: "Emily Carter",
    authorPosition: "Tech Analyst",
  },
  {
    category: "Trend",
    blogImg: "/assets/images/blog-img-3.jpg",
    title: "Top Skills Employers Look for in 2026",
    date: "5 December, 2025",
    authorImage: "/assets/images/user-avatar-3.png",
    authorName: "Michael Lee",
    authorPosition: "Career Coach",
  },
  {
    category: "Guide",
    blogImg: "/assets/images/blog-img-4.jpg",
    title: "Building a Successful Remote Team Culture",
    date: "10 January, 2026",
    authorImage: "/assets/images/user-avatar-1.png",
    authorName: "Sophia Patel",
    authorPosition: "HR Manager",
  },
];
